name: HotApps Nightly builds

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -configuration Debug
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: build/*/*.zip
