name: HotApps Release builds

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -configuration Debug
      run: xcodebuild build -configuration Release
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: build/*/*.zip
    - name: Upload app to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*/*.zip
        tag: ${{ github.ref }}
        file_glob: true

